// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Common.Users {
  internal static partial class UserContext
  {
    static readonly string __ServiceName = "common.users.UserContext";

    static readonly grpc::Marshaller<global::Common.Users.SubscribeRequest> __Marshaller_common_users_SubscribeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Common.Users.SubscribeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Common.Users.SubscribeReply> __Marshaller_common_users_SubscribeReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Common.Users.SubscribeReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Common.Users.PollRequest> __Marshaller_common_users_PollRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Common.Users.PollRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Common.Users.PollReply> __Marshaller_common_users_PollReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Common.Users.PollReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Common.Users.SubscribeRequest, global::Common.Users.SubscribeReply> __Method_Subscribe = new grpc::Method<global::Common.Users.SubscribeRequest, global::Common.Users.SubscribeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Subscribe",
        __Marshaller_common_users_SubscribeRequest,
        __Marshaller_common_users_SubscribeReply);

    static readonly grpc::Method<global::Common.Users.SubscribeRequest, global::Common.Users.SubscribeReply> __Method_Unsubscribe = new grpc::Method<global::Common.Users.SubscribeRequest, global::Common.Users.SubscribeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Unsubscribe",
        __Marshaller_common_users_SubscribeRequest,
        __Marshaller_common_users_SubscribeReply);

    static readonly grpc::Method<global::Common.Users.PollRequest, global::Common.Users.PollReply> __Method_Poll = new grpc::Method<global::Common.Users.PollRequest, global::Common.Users.PollReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Poll",
        __Marshaller_common_users_PollRequest,
        __Marshaller_common_users_PollReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Common.Users.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for UserContext</summary>
    public partial class UserContextClient : grpc::ClientBase<UserContextClient>
    {
      /// <summary>Creates a new client for UserContext</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UserContextClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UserContext that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UserContextClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UserContextClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UserContextClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Common.Users.SubscribeReply Subscribe(global::Common.Users.SubscribeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Subscribe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Common.Users.SubscribeReply Subscribe(global::Common.Users.SubscribeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Subscribe, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Users.SubscribeReply> SubscribeAsync(global::Common.Users.SubscribeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubscribeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Users.SubscribeReply> SubscribeAsync(global::Common.Users.SubscribeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Subscribe, null, options, request);
      }
      public virtual global::Common.Users.SubscribeReply Unsubscribe(global::Common.Users.SubscribeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Unsubscribe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Common.Users.SubscribeReply Unsubscribe(global::Common.Users.SubscribeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Unsubscribe, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Users.SubscribeReply> UnsubscribeAsync(global::Common.Users.SubscribeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnsubscribeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Users.SubscribeReply> UnsubscribeAsync(global::Common.Users.SubscribeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Unsubscribe, null, options, request);
      }
      public virtual global::Common.Users.PollReply Poll(global::Common.Users.PollRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Poll(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Common.Users.PollReply Poll(global::Common.Users.PollRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Poll, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Users.PollReply> PollAsync(global::Common.Users.PollRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PollAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Common.Users.PollReply> PollAsync(global::Common.Users.PollRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Poll, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UserContextClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UserContextClient(configuration);
      }
    }

  }
}
#endregion
