// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Common.Users {
  internal static partial class UserContext
  {
    static readonly string __ServiceName = "common.users.UserContext";

    static readonly grpc::Marshaller<global::Common.Users.SubscribeRequest> __Marshaller_common_users_SubscribeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Common.Users.SubscribeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Common.Users.SubscribeReply> __Marshaller_common_users_SubscribeReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Common.Users.SubscribeReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Common.Users.PollRequest> __Marshaller_common_users_PollRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Common.Users.PollRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Common.Users.PollReply> __Marshaller_common_users_PollReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Common.Users.PollReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Common.Users.SubscribeRequest, global::Common.Users.SubscribeReply> __Method_Subscribe = new grpc::Method<global::Common.Users.SubscribeRequest, global::Common.Users.SubscribeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Subscribe",
        __Marshaller_common_users_SubscribeRequest,
        __Marshaller_common_users_SubscribeReply);

    static readonly grpc::Method<global::Common.Users.SubscribeRequest, global::Common.Users.SubscribeReply> __Method_Unsubscribe = new grpc::Method<global::Common.Users.SubscribeRequest, global::Common.Users.SubscribeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Unsubscribe",
        __Marshaller_common_users_SubscribeRequest,
        __Marshaller_common_users_SubscribeReply);

    static readonly grpc::Method<global::Common.Users.PollRequest, global::Common.Users.PollReply> __Method_Poll = new grpc::Method<global::Common.Users.PollRequest, global::Common.Users.PollReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Poll",
        __Marshaller_common_users_PollRequest,
        __Marshaller_common_users_PollReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Common.Users.ServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UserContext</summary>
    [grpc::BindServiceMethod(typeof(UserContext), "BindService")]
    public abstract partial class UserContextBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Common.Users.SubscribeReply> Subscribe(global::Common.Users.SubscribeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Common.Users.SubscribeReply> Unsubscribe(global::Common.Users.SubscribeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Common.Users.PollReply> Poll(global::Common.Users.PollRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UserContextBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Subscribe, serviceImpl.Subscribe)
          .AddMethod(__Method_Unsubscribe, serviceImpl.Unsubscribe)
          .AddMethod(__Method_Poll, serviceImpl.Poll).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UserContextBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Subscribe, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Common.Users.SubscribeRequest, global::Common.Users.SubscribeReply>(serviceImpl.Subscribe));
      serviceBinder.AddMethod(__Method_Unsubscribe, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Common.Users.SubscribeRequest, global::Common.Users.SubscribeReply>(serviceImpl.Unsubscribe));
      serviceBinder.AddMethod(__Method_Poll, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Common.Users.PollRequest, global::Common.Users.PollReply>(serviceImpl.Poll));
    }

  }
}
#endregion
