// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: users.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ntreev.Crema.Services.Users {

  /// <summary>Holder for reflection information generated from users.proto</summary>
  internal static partial class UsersReflection {

    #region Descriptor
    /// <summary>File descriptor for users.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UsersReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgt1c2Vycy5wcm90bxIbbnRyZWV2LmNyZW1hLnNlcnZpY2VzLnVzZXJzGhln",
            "b29nbGUvcHJvdG9idWYvYW55LnByb3RvGgxjb21tb24ucHJvdG8yvwEKE0lV",
            "c2VyQ29udGV4dFNlcnZpY2USVAoGSW52b2tlEiQubnRyZWV2LmNyZW1hLnNl",
            "cnZpY2VzLkludm9rZVJlcXVlc3QaIi5udHJlZXYuY3JlbWEuc2VydmljZXMu",
            "SW52b2tlUmVwbHkiABJSCgRQb2xsEiIubnRyZWV2LmNyZW1hLnNlcnZpY2Vz",
            "LlBvbGxSZXF1ZXN0GiAubnRyZWV2LmNyZW1hLnNlcnZpY2VzLlBvbGxSZXBs",
            "eSIAKAEwAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Ntreev.Crema.Services.CommonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
