// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ntreev.Crema.Services {
  internal static partial class Adaptor
  {
    static readonly string __ServiceName = "ntreev.crema.services.Adaptor";

    static readonly grpc::Marshaller<global::Ntreev.Crema.Services.InvokeRequest> __Marshaller_ntreev_crema_services_InvokeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ntreev.Crema.Services.InvokeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ntreev.Crema.Services.InvokeReply> __Marshaller_ntreev_crema_services_InvokeReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ntreev.Crema.Services.InvokeReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ntreev.Crema.Services.PollRequest> __Marshaller_ntreev_crema_services_PollRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ntreev.Crema.Services.PollRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ntreev.Crema.Services.PollReply> __Marshaller_ntreev_crema_services_PollReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ntreev.Crema.Services.PollReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Ntreev.Crema.Services.InvokeRequest, global::Ntreev.Crema.Services.InvokeReply> __Method_Invoke = new grpc::Method<global::Ntreev.Crema.Services.InvokeRequest, global::Ntreev.Crema.Services.InvokeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Invoke",
        __Marshaller_ntreev_crema_services_InvokeRequest,
        __Marshaller_ntreev_crema_services_InvokeReply);

    static readonly grpc::Method<global::Ntreev.Crema.Services.PollRequest, global::Ntreev.Crema.Services.PollReply> __Method_Poll = new grpc::Method<global::Ntreev.Crema.Services.PollRequest, global::Ntreev.Crema.Services.PollReply>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Poll",
        __Marshaller_ntreev_crema_services_PollRequest,
        __Marshaller_ntreev_crema_services_PollReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ntreev.Crema.Services.CommonReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for Adaptor</summary>
    public partial class AdaptorClient : grpc::ClientBase<AdaptorClient>
    {
      /// <summary>Creates a new client for Adaptor</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public AdaptorClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Adaptor that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public AdaptorClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected AdaptorClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected AdaptorClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Ntreev.Crema.Services.InvokeReply Invoke(global::Ntreev.Crema.Services.InvokeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Invoke(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Ntreev.Crema.Services.InvokeReply Invoke(global::Ntreev.Crema.Services.InvokeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Invoke, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Ntreev.Crema.Services.InvokeReply> InvokeAsync(global::Ntreev.Crema.Services.InvokeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InvokeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Ntreev.Crema.Services.InvokeReply> InvokeAsync(global::Ntreev.Crema.Services.InvokeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Invoke, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Ntreev.Crema.Services.PollRequest, global::Ntreev.Crema.Services.PollReply> Poll(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Poll(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Ntreev.Crema.Services.PollRequest, global::Ntreev.Crema.Services.PollReply> Poll(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Poll, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override AdaptorClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AdaptorClient(configuration);
      }
    }

  }
}
#endregion
