// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: users.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ntreev.Crema.Services.Users {
  internal static partial class IUserContextService
  {
    static readonly string __ServiceName = "ntreev.crema.services.users.IUserContextService";

    static readonly grpc::Marshaller<global::Ntreev.Crema.Services.Users.InvokeRequest> __Marshaller_ntreev_crema_services_users_InvokeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ntreev.Crema.Services.Users.InvokeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ntreev.Crema.Services.Users.InvokeReply> __Marshaller_ntreev_crema_services_users_InvokeReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ntreev.Crema.Services.Users.InvokeReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ntreev.Crema.Services.Users.PollRequest> __Marshaller_ntreev_crema_services_users_PollRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ntreev.Crema.Services.Users.PollRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Ntreev.Crema.Services.Users.PollReply> __Marshaller_ntreev_crema_services_users_PollReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ntreev.Crema.Services.Users.PollReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Ntreev.Crema.Services.Users.InvokeRequest, global::Ntreev.Crema.Services.Users.InvokeReply> __Method_Invoke = new grpc::Method<global::Ntreev.Crema.Services.Users.InvokeRequest, global::Ntreev.Crema.Services.Users.InvokeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Invoke",
        __Marshaller_ntreev_crema_services_users_InvokeRequest,
        __Marshaller_ntreev_crema_services_users_InvokeReply);

    static readonly grpc::Method<global::Ntreev.Crema.Services.Users.PollRequest, global::Ntreev.Crema.Services.Users.PollReply> __Method_Poll = new grpc::Method<global::Ntreev.Crema.Services.Users.PollRequest, global::Ntreev.Crema.Services.Users.PollReply>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Poll",
        __Marshaller_ntreev_crema_services_users_PollRequest,
        __Marshaller_ntreev_crema_services_users_PollReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ntreev.Crema.Services.Users.UsersReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for IUserContextService</summary>
    public partial class IUserContextServiceClient : grpc::ClientBase<IUserContextServiceClient>
    {
      /// <summary>Creates a new client for IUserContextService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public IUserContextServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for IUserContextService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public IUserContextServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected IUserContextServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected IUserContextServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Ntreev.Crema.Services.Users.InvokeReply Invoke(global::Ntreev.Crema.Services.Users.InvokeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Invoke(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Ntreev.Crema.Services.Users.InvokeReply Invoke(global::Ntreev.Crema.Services.Users.InvokeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Invoke, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Ntreev.Crema.Services.Users.InvokeReply> InvokeAsync(global::Ntreev.Crema.Services.Users.InvokeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InvokeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Ntreev.Crema.Services.Users.InvokeReply> InvokeAsync(global::Ntreev.Crema.Services.Users.InvokeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Invoke, null, options, request);
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Ntreev.Crema.Services.Users.PollRequest, global::Ntreev.Crema.Services.Users.PollReply> Poll(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Poll(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Ntreev.Crema.Services.Users.PollRequest, global::Ntreev.Crema.Services.Users.PollReply> Poll(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Poll, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override IUserContextServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IUserContextServiceClient(configuration);
      }
    }

  }
}
#endregion
